File upload
flowacademyhu/kappa-meteo pull request #49
Opened 2021-07-06 12:48 UTC by fixo91

2021-07-06 14:30 UTC, akesztyus requested changes

2021-07-06 14:30 UTC, akesztyus commented on backend/src/main/java/hu/flowacademy/meteo/controller/FileUploadController.java
> +        String dataType = getDataType(file.getOriginalFilename());
Mivel nincs használva, akár mehet a 35-ös sorba is rögtön.

2021-07-06 14:30 UTC, akesztyus commented on backend/src/main/java/hu/flowacademy/meteo/controller/FileUploadController.java
> +            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).build();
Mindig 500 lesz,attól függetlenül, hogy esetleg a feltöltött file nem jó, arra inkább egy 4xx lenne való. Érdemes specifikus exception-t dobni file hiba esetén, és abból 400-at csinálni.

2021-07-06 14:30 UTC, akesztyus commented on backend/src/main/java/hu/flowacademy/meteo/controller/StationController.java
> +                collect(Collectors.toList());
Mit csinál vele a UI? Kell esetleg sorrendezés?

2021-07-06 14:30 UTC, akesztyus commented on backend/src/main/java/hu/flowacademy/meteo/service/FileUploadService.java
> +            log.debug("Found {} keys!!!", dataMap.size());
Ha talált kulcsok száma 2-nél kevesebb, akkor adat hiba van (biztosan lehet bátrabb állításokat is megfogalmazni), és lehet olyan exception-t dobni, amiből 400-as errort csinál a controller.

2021-07-06 17:37 UTC, Godfrid commented on backend/src/main/java/hu/flowacademy/meteo/controller/StationController.java
> +                collect(Collectors.toList());
Itt szerintem nem szukseges a dto, lehet egybol entitybol mappelni, mivel csak egy string lista megy ki. Szebb lenne ha a service-ben lenne egy method, ami ezt a listat adja vissza.

2021-07-06 19:11 UTC, SiposGergo commented on frontend/src/Upload/FileUploadLogic.js
> +        console.log(response);
Logot vegyük ki.

2021-07-06 19:11 UTC, SiposGergo commented on frontend/src/Upload/FileUploadLogic.js
> +    console.warn(file);
Warn-t vegyük ki.

2021-07-06 19:12 UTC, SiposGergo commented on frontend/src/Upload/FileUploadLogic.js
> +        console.warn(res);
Warn-t vegyük ki.

2021-07-06 19:12 UTC, SiposGergo commented on frontend/src/Upload/FileUploadLogic.js
> +        console.log(error.message);
Console.error

2021-07-06 21:20 UTC, fixo91 commented on frontend/src/Upload/FileUploadLogic.js
> +        console.log(response);
Javitva

2021-07-06 21:21 UTC, fixo91 commented on frontend/src/Upload/FileUploadLogic.js
> +    console.warn(file);
Javitva

2021-07-06 21:22 UTC, fixo91 commented on frontend/src/Upload/FileUploadLogic.js
> +        console.warn(res);
Javitva

2021-07-06 21:24 UTC, fixo91 commented on frontend/src/Upload/FileUploadLogic.js
> +        console.log(error.message);
Javitva

2021-07-07 08:35 UTC, VassTamas87 commented
Visszaraktam pár modsítást a feltöltéshez. Dátum formázás miatt. Azért mert így feltudjok tölteni a szegedi adatokat is. És ezt azért szeretném mert ott vn a legtöbb adatunk. Mind a 20 méréshez van adat, míg a többi 10 állomás csv-éiben átlagosan csa 10 méréshet van adtunk.

2021-07-07 11:29 UTC, akesztyus requested changes

2021-07-07 11:29 UTC, akesztyus commented on backend/src/main/java/hu/flowacademy/meteo/service/FileUploadService.java
> +                throw new ValidationException("Error while reading file");
Az igaz, hogy hiba, de milyen? Ez valami "Invalid file format" lehetne.

2021-07-07 14:06 UTC, akesztyus approved these changes

2021-07-07 14:12 UTC, merged